### ISSUE TITLE
Bets made as exploding messages aren't registered

### ISSUE THREAD

**Issue by zackster** [codeforcash/croupier#93]

**Comment by zackster** [comment]
@ellipticcurv3 fixed

**Comment by zackster** [comment]
@ellipticcurv3 I spoke too soon,

I'm now getting the error

Error: This exploding message is not available to you
    at Interface.onLine (/Users/zackburt/keybase/zb-bot/keybase-bot.js:1194:17)
    at Interface.emit (events.js:182:13)
    at Interface.EventEmitter.emit (domain.js:442:20)
    at Interface._onLine (readline.js:285:10)
    at Interface._normalWrite (readline.js:428:12)
    at Socket.ondata (readline.js:144:10)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:277:12)
    at readableAddChunk (_stream_readable.js:262:11)

**Comment by ellipticcurv3** [comment]
@zackster are you running the bot on a provisioned device or with a paper key?

**Comment by zackster** [comment]
Yes, paper key since we're using the https://github.com/keybase/keybase-bot library

If there is a node js solution for using a provisioned device then we could probably add that in, why not?  cc @pzduniak & @malgorithms

**Comment by ellipticcurv3** [comment]
Well, if you use paper keys it's not possible to read exploding messages, as far as I know. I've read that somewhere in the Keybase documentation. So that's why you can't read them :) I'll take a look into that repo asap

**Comment by pzduniak** [comment]
https://github.com/keybase/keybase-bot/pull/129

You basically have to run `initFromRunningService` with a provisioned device. Keep in mind that you'll have to persist the service's config directories.

**Comment by zackster** [comment]
Fixed, thanks

**Comment by zackster** [comment]
@pzduniak if using this on AWS lambda, is there a way to persist the service's config directories? 

On lambda, can only write to the /tmp directory - no other fs writes are allowed.
So is there a param or set of config vars or envvars one can set in order to force everything to go into /tmp?
